### ISSUE TITLE
ug.h ERROR C2365

### ISSUE THREAD

**Issue by qazxsw1597532018** [alxbrn/universal-graphics-hook#1]
![screenshot](https://user-images.githubusercontent.com/58576503/70839283-e55c7b80-1e03-11ea-9dec-496014635ee9.png)

**Comment by alxbrn** [comment]
If you keep opening stupid issues in my github repos, then I will block you. Issue closed.

**Comment by sols000** [comment]
> If you keep opening stupid issues in my github repos, then I will block you. Issue closed.

your enums is not in a namespace ,so maybe you have made a stupid issue!
